sudo: false
language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@^6.0.0
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release