sudo: false
language: node_js

node_js:
  -10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test:single
after_success:
  - npm run semantic-release